import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { Letter, LetterService } from 'src/app/services/letter.service';

@Component({
  selector: 'app-info-popup',
  templateUrl: './info-popup.component.html',
  styleUrls: ['./info-popup.component.css']
})
export class InfoPopupComponent implements OnInit {

  public infoHeaderLetters: Letter[] = this.letterService.generateRansomText('so you need some help, eh?', 5, {'cursor': 'default'}, {randomColors: true});
  public ransomText = '';

  public versionHistory = [
    {
      version: '0.3',
      date: 'Nov 13, 2022',
      changes: [
        'Fixed incorrect coloring of certain letter guesses, thanks to Kerry for pointing this out',
        'Added coloring of all letters based on guesses made; colors yoinked from wordle site',
        'Completely rebuilt header with bootstrap navbar style',
        'Added nav button for linking to root site and moved help button to inside button',
        'Made adjustments to guess fields'
      ]
    },
    {
      version: '0.2',
      date: 'Nov 11, 2022',
      changes: [
        'Added new word every day, taken from list of all wordle words.',
        'Added new ransom note every day, generated by selecting words and phrases from several arrays.',
        'Added proper letter highlighting for letters in the word in but in the wrong place.'
      ]
    },
    {
      version: '0.1',
      date: 'Nov 5, 2022',
      changes: [
        'Inital Release',
      ]
    },
    // {
    //   version: '',
    //   date: '',
    //   changes: [
    //     '',
    //   ]
    // },
  ];

  @Output() closePopup = new EventEmitter<void>();

  constructor(private letterService: LetterService) { }

  ngOnInit(): void {
    for(let letter of this.infoHeaderLetters) {
      if(letter.letter === ' ') {
        letter.style = {...letter.style, 'margin-left': '3vmax'};
      }
    }
  }

  public onClosePopup(): void {
    this.closePopup.next();
  }

  public onGenerateRansom():void {
    this.ransomText = this.letterService.randomRansomString(Math.floor(Math.random()*1000000));
  }

}
